language: cpp
dist: xenial

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq imagemagick freeglut3-dev libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev

script:
- cd Builds/Linux/; make -j$(nproc)
- mkdir -p appdir/usr/bin
- mkdir -p appdir/usr/share/icons/hicolor/256x256/apps
- convert ../../Resources/ui/dexedIcon.png -resize 256x256 appdir/usr/share/icons/hicolor/256x256/apps/dexed.png
- cp appdir/usr/share/icons/hicolor/256x256/apps/dexed.png appdir/

after_success:
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh APPNAME*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
